default_context:
    author_name: "Jane Doe"
    author_email: "jane@website.com"
    hosting_github_username_or_org: "JaneCodes"
    project_name: "Python Boilerplate"
    project_slug: "python-boilerplate"
    python_slug: "python_boilerplate"
    project_short_description: "Python Boilerplate contains all the boilerplate you need to create a Python package."
    hosting_pypi_username: "JaneCodes"
    version: "0.0.0"
    license: "MIT License"