default_context:
    name: "Jane Doe"
    email: "jane@website.com"
    github_username: "JaneCodes"
    project_name: "Python Boilerplate"
    project_slug: "python-boilerplate"
    python_slug: "python_boilerplate"
    project_short_description: "Python Boilerplate contains all the boilerplate you need to create a Python package."
    pypi_username: "JaneCodes"
    version: "0.0.0"
    license: "MIT License"