# list all available commands
default:
  just --list

# clean all build, python, and lint files
{% raw %}clean:
	rm -fr {{justfile_directory()}}/build/
	rm -fr {{justfile_directory()}}/docs/_build/
	rm -fr {{justfile_directory()}}/dist/
	rm -fr {{justfile_directory()}}/.eggs/
	find {{justfile_directory()}}/ -name '*.egg-info' -exec rm -fr {} +
	find {{justfile_directory()}}/ -name '*.egg' -exec rm -f {} +
	find {{justfile_directory()}}/ -name '*.pyc' -exec rm -f {} +
	find {{justfile_directory()}}/ -name '*.pyo' -exec rm -f {} +
	find {{justfile_directory()}}/ -name '*~' -exec rm -f {} +
	find {{justfile_directory()}}/ -name '__pycache__' -exec rm -fr {} +
	rm -fr {{justfile_directory()}}/.coverage
	rm -fr {{justfile_directory()}}/coverage.xml
	rm -fr {{justfile_directory()}}/htmlcov/
	rm -fr {{justfile_directory()}}/.pytest_cache
	rm -fr {{justfile_directory()}}/.mypy_cache{% endraw %}

# install with all deps
install:
	pip install -e {% raw %}{{justfile_directory()}}{% endraw %}[lint,test,docs,dev]

# lint, format, and check all files
lint:
	pre-commit run --all-files

# run tests
test:
	pytest --cov-report xml --cov-report html --cov={{ cookiecutter.python_slug }} {% raw %}{{justfile_directory()}}{% endraw %}/{{ cookiecutter.python_slug }}/tests/

# run lint and then run tests
build:
	just lint
	just test

# generate Sphinx HTML documentation
generate-docs:
	rm -f {% raw %}{{justfile_directory()}}{% endraw %}/docs/{{ cookiecutter.python_slug }}*.rst
	rm -f {% raw %}{{justfile_directory()}}{% endraw %}/docs/modules.rst
	sphinx-apidoc -o {% raw %}{{justfile_directory()}}{% endraw %}/docs/ {{ cookiecutter.python_slug }} {% raw %}{{justfile_directory()}}{% endraw %}/**/tests/
	python -msphinx "{% raw %}{{justfile_directory()}}{% endraw %}/docs/" "{% raw %}{{justfile_directory()}}{% endraw %}/docs/_build/"

# generate Sphinx HTML documentation and serve to browser
serve-docs:
	just generate-docs
	python -mwebbrowser -t file://{% raw %}{{justfile_directory()}}{% endraw %}/docs/_build/index.html

# tag a new version
tag-for-release version:
	git tag -a {% raw %}"{{version}}" -m "{{version}}"{% endraw %}
	echo "Tagged: $(git tag --sort=-version:refname| head -n 1)"

# release a new version
release:
	git push --follow-tags

# update this repo using latest cookiecutter-py-package
update-from-cookiecutter:
	cookiecutter gh:evamaxfield/cookiecutter-py-package --config-file {% raw %}{{justfile_directory()}}{% endraw %}/.cookiecutter.yaml --no-input --overwrite-if-exists --output-dir {% raw %}{{justfile_directory()}}{% endraw %}/..